editURL = "https://github.com/GamesInTheBox-MC/Docs/edit/main/content/"
description = "The Documentation for GamesInTheBox & its expansions"
author.name = "HSGamer"
showVisitedLinks = true
disableSearchHiddenPages = true
disableSeoHiddenPages = true
disableTagHiddenPages = true
collapsibleMenu = true
disableInlineCopyToClipBoard = true
disableNextPrev = false
disableSwagger = true
disableMathJax = true
disableLandingPageButton = true
themeVariant = [ "auto" ]
